baseurl             = "http://abizern.org/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-GB"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa-eh"
author              = "Abizer Nasir"
title               = "Abizern.org"
#pygmentsuseclasses  = true
pluralizelisttitles = false
googleAnalytics     = "UA-5015208-5"



[permalinks]
blog                = "/:year/:title/"
talks               = "/talks/:year/:title/"
notes               = "/notes/:title/"

[taxonomies]
tag                 = "tags"

# [[menu.main]]
# name                = "Home"
# weight              = -120
# identifier          = "home"
# url                 = "/"

# [[menu.main]]
# name                = "About"
# weight              = -110
# identifier          = "about"
# url                 = "/about/"

# [[menu.main]]
# name                = "Posts"
# weight              = -100
# identifier          = "posts"
# url                 = "/posts/"

# [[menu.main]]
# name                = "Talks"
# weight              = -90
# identifier          = "talks"
# url                 = "/talks/"

# [[menu.main]]
# name                = "Notes"
# weight              = -80
# identifier          = "notes"
# url                 = "/notes/"

[params]
latestpostscount       = 8                             # how many posts to display on the home page
author                 = "Abizer Nasir"
dateform               = "Jan 2, 2006"
dateformfull           = "January 2, 2006"
description            = "Opinions and £1 will get me a small coffee."
copyright              = "© 2009-2017 Abizer Nasir"
copyrightUrl           = "https://creativecommons.org/licenses/by-sa/4.0/"
faviconfile            = "favicon.png"
logofile               = "avatar.jpg"
#extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.

email                  = "abizern@abizern.org"
github                 = "Abizern"
instagram              = "abizern"
linkedin               = "abizern"
twitter                = "abizern"
noshowreadtime         = true                         # if true, don't show "<x> minutes read" in posts

highlightjs            = true
highlightjslanguages   = ["go", "haskell", "swift", "objectivec", "elm", "ruby"]                        # additional languages not included in the "common" set
highlightjsStyle       = "dracula"

piwik                  = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id             = 2                             # Id of your site in Piwik

# avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = "f28c4835c9e2277b6e04b86574532a2d"

